# Build Spec for AWS CodeBuild CI

version: 0.2
env:
  variables:
    use_current_branch: "true"
    enable_smdataparallel_tests: "true"
    use_default_horovod_version: "false"
    force_run_tests: "false"
    framework: "tensorflow"
phases:
  build:
    commands:
      - chmod +x config/profiler/run_profiler_integration_tests.sh && ./config/profiler/run_profiler_integration_tests.sh
